<?php

declare(strict_types=1);
return [
    // 模块元数据
    'module' => [
        'key' => 'notification',
        'name' => '通知配置',
        'description' => '消息通知相关配置，包括短信、邮件、站内信等',
        'icon' => 'icon-park-outline:remind',
        'sort' => 3,
    ],

    // 配置分组
    'groups' => [
        [
            'key' => 'sms',
            'name' => '短信配置',
            'description' => '短信通知配置（阿里云短信）',
            'icon' => 'icon-park-outline:sms',
            'sort' => 1,
            'items' => [
                [
                    'key' => 'enabled',
                    'name' => '启用短信通知',
                    'description' => '是否启用短信通知功能',
                    'type' => 'switch',
                    'default_value' => '0',
                    'sort' => 1,
                ],
                [
                    'key' => 'access_key_id',
                    'name' => 'AccessKey ID',
                    'description' => '阿里云 AccessKey ID',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 100],
                    'is_encrypted' => 1,
                    'sort' => 2,
                ],
                [
                    'key' => 'access_key_secret',
                    'name' => 'AccessKey Secret',
                    'description' => '阿里云 AccessKey Secret',
                    'type' => 'password',
                    'default_value' => '',
                    'validation' => ['max' => 100],
                    'is_encrypted' => 1,
                    'sort' => 3,
                ],
                [
                    'key' => 'sign_name',
                    'name' => '短信签名',
                    'description' => '短信签名名称',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 50],
                    'placeholder' => '例如：贵客家票务',
                    'sort' => 4,
                ],
                [
                    'key' => 'template_code_verify',
                    'name' => '验证码模板ID',
                    'description' => '验证码短信模板CODE',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 50],
                    'placeholder' => 'SMS_123456789',
                    'sort' => 5,
                ],
                [
                    'key' => 'template_code_notify',
                    'name' => '通知模板ID',
                    'description' => '订单通知短信模板CODE',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 50],
                    'placeholder' => 'SMS_987654321',
                    'sort' => 6,
                ],
            ],
        ],
        [
            'key' => 'email',
            'name' => '邮件配置',
            'description' => '邮件通知配置（SMTP）',
            'icon' => 'icon-park-outline:mail',
            'sort' => 2,
            'items' => [
                [
                    'key' => 'enabled',
                    'name' => '启用邮件通知',
                    'description' => '是否启用邮件通知功能',
                    'type' => 'switch',
                    'default_value' => '0',
                    'sort' => 1,
                ],
                [
                    'key' => 'host',
                    'name' => 'SMTP服务器',
                    'description' => 'SMTP 服务器地址',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 100],
                    'placeholder' => 'smtp.example.com',
                    'sort' => 2,
                ],
                [
                    'key' => 'port',
                    'name' => '端口',
                    'description' => 'SMTP 服务器端口',
                    'type' => 'number',
                    'default_value' => '465',
                    'validation' => ['min' => 1, 'max' => 65535],
                    'sort' => 3,
                ],
                [
                    'key' => 'username',
                    'name' => '用户名',
                    'description' => 'SMTP 用户名',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 100],
                    'sort' => 4,
                ],
                [
                    'key' => 'password',
                    'name' => '密码',
                    'description' => 'SMTP 密码或授权码',
                    'type' => 'password',
                    'default_value' => '',
                    'validation' => ['max' => 100],
                    'is_encrypted' => 1,
                    'sort' => 5,
                ],
                [
                    'key' => 'from_address',
                    'name' => '发件人地址',
                    'description' => '发件人邮箱地址',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 100, 'email' => true],
                    'placeholder' => 'noreply@example.com',
                    'sort' => 6,
                ],
                [
                    'key' => 'from_name',
                    'name' => '发件人名称',
                    'description' => '发件人显示名称',
                    'type' => 'text',
                    'default_value' => '贵客家票务',
                    'validation' => ['max' => 50],
                    'sort' => 7,
                ],
                [
                    'key' => 'encryption',
                    'name' => '加密方式',
                    'description' => 'SMTP 加密方式',
                    'type' => 'select',
                    'default_value' => 'ssl',
                    'options' => [
                        ['label' => 'SSL', 'value' => 'ssl'],
                        ['label' => 'TLS', 'value' => 'tls'],
                        ['label' => '无加密', 'value' => ''],
                    ],
                    'sort' => 8,
                ],
            ],
        ],
        [
            'key' => 'order_notify',
            'name' => '订单通知',
            'description' => '订单相关通知配置',
            'icon' => 'icon-park-outline:transaction-order',
            'sort' => 3,
            'items' => [
                [
                    'key' => 'channels',
                    'name' => '通知渠道',
                    'description' => '订单状态变更时的通知渠道',
                    'type' => 'multiSelect',
                    'default_value' => [],
                    'options' => [
                        ['label' => '短信', 'value' => 'sms'],
                        ['label' => '邮件', 'value' => 'email'],
                        ['label' => '站内信', 'value' => 'internal'],
                        ['label' => '微信模板消息', 'value' => 'wechat'],
                    ],
                    'sort' => 1,
                ],
                [
                    'key' => 'notify_on_create',
                    'name' => '订单创建通知',
                    'description' => '订单创建成功时是否发送通知',
                    'type' => 'switch',
                    'default_value' => '0',
                    'sort' => 2,
                ],
                [
                    'key' => 'notify_on_pay',
                    'name' => '支付成功通知',
                    'description' => '支付成功时是否发送通知',
                    'type' => 'switch',
                    'default_value' => '1',
                    'sort' => 3,
                ],
                [
                    'key' => 'notify_on_cancel',
                    'name' => '订单取消通知',
                    'description' => '订单取消时是否发送通知',
                    'type' => 'switch',
                    'default_value' => '1',
                    'sort' => 4,
                ],
                [
                    'key' => 'notify_on_refund',
                    'name' => '退款成功通知',
                    'description' => '退款成功时是否发送通知',
                    'type' => 'switch',
                    'default_value' => '1',
                    'sort' => 5,
                ],
            ],
        ],
    ],
];
