<?php

declare(strict_types=1);
return [
    // 模块元数据
    'module' => [
        'key' => 'payment',
        'name' => '支付配置',
        'description' => '支付相关配置，包括微信支付、支付宝等',
        'icon' => 'icon-park-outline:pay-code-one',
        'sort' => 2,
    ],

    // 配置分组
    'groups' => [
        [
            'key' => 'wechat',
            'name' => '微信支付',
            'description' => '微信支付配置',
            'icon' => 'simple-icons:wechat',
            'sort' => 1,
            'items' => [
                [
                    'key' => 'enabled',
                    'name' => '启用微信支付',
                    'description' => '是否启用微信支付渠道',
                    'type' => 'switch',
                    'default_value' => '0',
                    'sort' => 1,
                ],
                [
                    'key' => 'app_id',
                    'name' => 'AppID',
                    'description' => '微信支付 AppID',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 50],
                    'placeholder' => '请输入微信支付 AppID',
                    'is_encrypted' => 1,
                    'sort' => 2,
                ],
                [
                    'key' => 'mch_id',
                    'name' => '商户号',
                    'description' => '微信支付商户号',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 50],
                    'placeholder' => '请输入商户号',
                    'is_encrypted' => 1,
                    'sort' => 3,
                ],
                [
                    'key' => 'api_key',
                    'name' => 'API密钥',
                    'description' => '微信支付 API 密钥（v2）',
                    'type' => 'password',
                    'default_value' => '',
                    'validation' => ['max' => 100],
                    'is_encrypted' => 1,
                    'sort' => 4,
                ],
                [
                    'key' => 'api_v3_key',
                    'name' => 'API v3密钥',
                    'description' => '微信支付 API v3 密钥',
                    'type' => 'password',
                    'default_value' => '',
                    'validation' => ['max' => 100],
                    'is_encrypted' => 1,
                    'sort' => 5,
                ],
                [
                    'key' => 'cert_path',
                    'name' => '证书路径',
                    'description' => '微信支付证书文件路径',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 255],
                    'placeholder' => '/data/cert/wechat/apiclient_cert.pem',
                    'sort' => 6,
                ],
            ],
        ],
        [
            'key' => 'alipay',
            'name' => '支付宝',
            'description' => '支付宝支付配置',
            'icon' => 'simple-icons:alipay',
            'sort' => 2,
            'items' => [
                [
                    'key' => 'enabled',
                    'name' => '启用支付宝',
                    'description' => '是否启用支付宝支付渠道',
                    'type' => 'switch',
                    'default_value' => '0',
                    'sort' => 1,
                ],
                [
                    'key' => 'app_id',
                    'name' => 'AppID',
                    'description' => '支付宝应用 ID',
                    'type' => 'text',
                    'default_value' => '',
                    'validation' => ['max' => 50],
                    'placeholder' => '请输入支付宝应用 ID',
                    'is_encrypted' => 1,
                    'sort' => 2,
                ],
                [
                    'key' => 'private_key',
                    'name' => '应用私钥',
                    'description' => '支付宝应用私钥',
                    'type' => 'textarea',
                    'default_value' => '',
                    'is_encrypted' => 1,
                    'sort' => 3,
                ],
                [
                    'key' => 'public_key',
                    'name' => '支付宝公钥',
                    'description' => '支付宝公钥',
                    'type' => 'textarea',
                    'default_value' => '',
                    'is_encrypted' => 1,
                    'sort' => 4,
                ],
            ],
        ],
        [
            'key' => 'general',
            'name' => '通用设置',
            'description' => '支付通用配置',
            'icon' => 'icon-park-outline:settings',
            'sort' => 3,
            'items' => [
                [
                    'key' => 'timeout_minutes',
                    'name' => '支付超时时间',
                    'description' => '支付创建后未完成自动关闭的时间（分钟）',
                    'type' => 'number',
                    'default_value' => '15',
                    'validation' => ['min' => 1, 'max' => 120],
                    'tooltip' => '建议设置为 10-30 分钟',
                    'sort' => 1,
                ],
                [
                    'key' => 'notify_retry_times',
                    'name' => '通知重试次数',
                    'description' => '支付回调通知失败后的重试次数',
                    'type' => 'number',
                    'default_value' => '3',
                    'validation' => ['min' => 0, 'max' => 10],
                    'sort' => 2,
                ],
            ],
        ],
    ],
];
